- GUI/coregui/Models/ComboProperty.cpp
- GUI/coregui/Models/ComboProperty.h
- GUI/coregui/Models/IntensityDataItem.cpp
- GUI/coregui/Models/ItemFactory.cpp
- GUI/coregui/Models/JobItemHelper.cpp
- GUI/coregui/Models/LinkInstrumentItem.cpp
- GUI/coregui/Models/LinkInstrumentItem.h
- GUI/coregui/Models/ModelMapper.cpp
- GUI/coregui/Models/RealDataItem.cpp
- GUI/coregui/Models/RealDataItem.h
- GUI/coregui/Models/RealDataModel.cpp
- GUI/coregui/Models/RealDataModel.h
- GUI/coregui/Models/item_constants.h
- GUI/coregui/Views/ImportDataWidgets/ImportDataAssistant.cpp
- GUI/coregui/Views/ImportDataWidgets/ImportDataAssistant.h
- GUI/coregui/Views/ImportDataWidgets/LinkInstrumentManager.cpp
- GUI/coregui/Views/ImportDataWidgets/LinkInstrumentManager.h
- GUI/coregui/Views/ImportDataWidgets/RealDataPropertiesWidget.cpp
- GUI/coregui/Views/ImportDataWidgets/RealDataPropertiesWidget.h
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorWidget.cpp
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorWidget.h
- GUI/coregui/Views/PropertyEditor/PropertyVariantFactory.cpp
- GUI/coregui/Views/PropertyEditor/PropertyVariantManager.cpp
- GUI/coregui/mainwindow/mainwindow.cpp
- GUI/coregui/utils/GUIHelpers.cpp
- GUI/coregui/utils/GUIHelpers.h
- GUI/main/main.cpp
- Tests/UnitTests/GUI/CMakeLists.txt
- Tests/UnitTests/GUI/TestComboProperty.h
- Tests/UnitTests/GUI/TestGUI.cpp
Implemented linking between RealDataItem and InstrumentItem: 
- adapts instrument binning to match real data, if necessary
- automatically tracks changes in instrument layout (xmin, xmax) and propagates to RealData image
- disables linking if instrument binning has suddenly changed
- preserves linking state after save/load
Item http://apps.jcns.fz-juelich.de/redmine/issues/1488 is now 75% ready.
> Instrument link

- CHANGELOG
We should try to formulate our release more attractively, in more complete sentences, and in less technical terms. This cannot be done in the last minute of release day; the text needs some time to mature, and it needs consideration of all of us. Therefore I propose that from now on release news are prepared by successive edits to CHANGELOG.
> New procedure to prepare release news, and first draft for 1.7

- Core/Parametrization/ParameterSample.h
- Wrap/swig/libBornAgainCore.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainFit_wrap.cpp
This pull request addresses issue 1689 from our internal tracker. `ParameterSample` and `std::vector<ParameterSample>` are now properly exported to the Python bindings.
> add ParameterSample to swig exports

- Core/Aggregate/InterferenceFunction2DParaCrystal.cpp
- Core/Aggregate/InterferenceFunction2DParaCrystal.h
- Core/Aggregate/InterferenceFunctionRadialParaCrystal.cpp
- Core/Aggregate/InterferenceFunctionRadialParaCrystal.h
- Core/Multilayer/Layer.cpp
- Core/Multilayer/Layer.h
- Core/Multilayer/MultiLayer.cpp
- Core/Multilayer/MultiLayer.h
- Core/Parametrization/INode.cpp
- Core/Parametrization/INode.h
- Core/Parametrization/NodeUtils.cpp
- Core/Parametrization/NodeUtils.h
- Core/Particle/Particle.cpp
- Core/Particle/Particle.h
- Core/Particle/ParticleDistribution.cpp
- Core/Particle/ParticleDistribution.h
- Core/Scattering/ISample.cpp
- Core/Scattering/ISample.h
- Core/Scattering/ISampleIteratorStrategy.cpp
- Core/Scattering/ISampleIteratorStrategy.h
- Core/Scattering/ISampleVisitor.cpp
- Core/Scattering/ISampleVisitor.h
- Core/Scattering/SampleTreeIterator.cpp
- Core/Scattering/SampleTreeIterator.h
- Examples/python/simulation/ex01_BasicParticles/CylindersAndPrisms.py
- Tests/UnitTests/Core/Sample/MultiLayerTest.h
- Wrap/swig/directors.i
- Wrap/swig/libBornAgainCore.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainCore_wrap.h
* New class INode (name can be changed) is introduced between IParameterized and ISample.
* All existing children bookkeeping activity is moved from ISample up to INode.
* ISample::to_str is removed from everywhere in the favor of single INode::to_str()
In the following I'm going to make INode actually own its children, provide unit tests and make some renaming.
> New INode tree hierarchy

- Core/Fitting/FitSuiteImpl.cpp
- GUI/coregui/Models/FitParameterItems.cpp
- GUI/coregui/Models/JobItem.cpp
- GUI/coregui/Models/JobItem.h
- GUI/coregui/Models/JobQueueData.cpp
- GUI/coregui/Views/FitWidgets/RunFitControlWidget.cpp
- GUI/coregui/Views/FitWidgets/RunFitControlWidget.h
- GUI/coregui/Views/InfoWidgets/DistributionWidget.cpp
- GUI/coregui/Views/InfoWidgets/DistributionWidget.h
- GUI/coregui/Views/InfoWidgets/InfoWidget.cpp
- GUI/coregui/Views/InfoWidgets/PySampleWidget.cpp
- GUI/coregui/Views/InfoWidgets/PySampleWidget.h
- GUI/coregui/Views/InfoWidgets/WarningSign.cpp
- GUI/coregui/Views/InfoWidgets/WarningSign.h
- GUI/coregui/Views/InfoWidgets/WarningSignWidget.cpp
- GUI/coregui/Views/InfoWidgets/WarningSignWidget.h
- GUI/coregui/Views/JobWidgets/ParameterTuningWidget.cpp
- GUI/coregui/Views/JobWidgets/ParameterTuningWidget.h
- GUI/coregui/Views/SimulationWidgets/PythonScriptWidget.cpp
- GUI/coregui/Views/SimulationWidgets/PythonScriptWidget.h
To unify the usage of WarningSign across the project and reduce code duplication. This resolves [Item 1492](http://apps.jcns.fz-juelich.de/redmine/issues/1492).
> WarningSign refactoring

- Core/InputOutput/TiffHandler.cpp
- Core/InputOutput/TiffHandler.h
The TIFF file from A. Nent has 16b samples. TiffHandler is modified to read 32b floats, and 8, 16, and 32b integer samples.
> Feature #1769

- Core/Multilayer/MultiLayer.cpp
- Core/Multilayer/MultiLayer.h
- Core/Particle/IParticle.cpp
- Core/Particle/IParticle.h
- Core/Particle/MesoCrystal.cpp
- Core/Particle/MesoCrystal.h
- Core/Particle/Particle.cpp
- Core/Particle/Particle.h
- Core/Particle/ParticleComposition.cpp
- Core/Particle/ParticleComposition.h
- Core/Particle/ParticleCoreShell.cpp
- Core/Particle/ParticleCoreShell.h
- Core/Particle/SlicedFormFactorList.cpp
- Core/Particle/ZLimits.cpp
- Core/Particle/ZLimits.h
- Core/Scattering/IFormFactor.cpp
- Core/Scattering/IFormFactor.h
- auto/Wrap/doxygen_core.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainCore_wrap.h
- auto/Wrap/libBornAgainFit_wrap.cpp
During the collection of form factors, the software now generates a sliced form factor for each layer that contains (part of) the shapes. For the moment, only when the elementary shape, i.e. not a composition, is completely contained in a layer, will the form factor be generated. Otherwise, an exception is thrown.
> Phase 1 of sliced form factors

- Core/Particle/SlicedFormFactorList.cpp
- Core/Scattering/IFormFactor.cpp
This happens for example when:
Create truncated sphere particle in substrate with rotation of 180 degrees around y-axis (no translation)
> Allow for relatively small crossing of interfaces for particles

- GUI/coregui/Models/BeamDistributionItem.cpp
- GUI/coregui/Models/DetectorItems.cpp
- GUI/coregui/Models/GroupInfo.cpp
- GUI/coregui/Models/GroupInfo.h
- GUI/coregui/Models/GroupInfoCatalogue.cpp
- GUI/coregui/Models/GroupInfoCatalogue.h
- GUI/coregui/Models/GroupProperty.cpp
- GUI/coregui/Models/GroupProperty.h
- GUI/coregui/Models/GroupPropertyRegistry.cpp
- GUI/coregui/Models/GroupPropertyRegistry.h
- GUI/coregui/Models/InstrumentItem.cpp
- GUI/coregui/Models/InterferenceFunctionItems.cpp
- GUI/coregui/Models/LayerItem.cpp
- GUI/coregui/Models/MinimizerItem.cpp
- GUI/coregui/Models/ParticleDistributionItem.cpp
- GUI/coregui/Models/ParticleItem.cpp
- GUI/coregui/Models/SessionItem.cpp
- GUI/coregui/Models/SessionItem.h
- GUI/coregui/Models/SessionXML.cpp
- GUI/coregui/Models/TransformToDomain.cpp
- GUI/coregui/Views/InfoWidgets/DistributionWidget.cpp
- GUI/coregui/Views/PropertyEditor/PropertyBrowserUtils.cpp
- GUI/coregui/Views/PropertyEditor/PropertyVariantManager.cpp
- GUI/coregui/Views/SampleDesigner/ParticleView.cpp
- Tests/UnitTests/GUI/TestGroupProperty.h
- Tests/UnitTests/GUI/TestParameterTreeUtils.h
- Tests/UnitTests/GUI/TestParticleDistributionItem.h
- dev-tools/log/perf_history.txt
New GroupInfo and GroupInfoCatalogue are introduced to provide default type for group item construction (instead of previous alphabetical one).
> GroupProperty refactoring

- Core/Material/BaseMaterialImpl.cpp
- Core/Material/BaseMaterialImpl.h
- Core/Material/Material.cpp
- Core/Material/Material.h
- Core/Material/MaterialFactoryFuncs.cpp
- Core/Material/MaterialFactoryFuncs.h
- Core/Material/RefractiveCoefMaterial.cpp
- Core/Material/RefractiveCoefMaterial.h
- Core/Material/WavelengthIndependentMaterial.cpp
- Core/Material/WavelengthIndependentMaterial.h
- Doc/Doxygen/defgroups.dox
- Tests/UnitTests/Core/Other/MaterialTest.h
- Tests/UnitTests/Core/Other/testlist.h
Now material must be created with a number of factory functions. Material class contains a pointer to implementation, which can be either analogous to old HomogeneousMaterial or implement material with wavelength-independent data.
ComputationTest in MaterialTest.h shows the usage and also verifies validity of created wavelength-independent material
> Redmine issue 1858: implementation of material class embracing wavelength-independent data

- CMakeLists.txt
- cmake/bornagain/modules/SearchInstalledSoftware.cmake
- cmake/bornagain/modules/ValidatePythonInstallation.cmake
File BornAgainMacros.cmake contained one single macro.
Therefore renamed. Moved include statement.
> Renamed BornAgainMacros.cmake

- Core/Binning/SimulationElement.cpp
- Core/Binning/SimulationElement.h
- Core/Computation/ConstantBackground.cpp
- Core/Computation/ConstantBackground.h
- Core/Computation/DWBAComputation.cpp
- Core/Computation/DWBAComputation.h
- Core/Computation/IBackground.cpp
- Core/Computation/IBackground.h
- Core/Computation/IComputation.cpp
- Core/Computation/IComputation.h
- Core/Computation/PoissonNoiseBackground.cpp
- Core/Computation/PoissonNoiseBackground.h
- Core/Computation/SpecularComputation.cpp
- Core/Computation/SpecularComputation.h
- Core/Parametrization/SimulationOptions.cpp
- Core/Parametrization/SimulationOptions.h
- Core/Parametrization/ThreadInfo.h
- Core/Simulation/GISASSimulation.cpp
- Core/Simulation/GISASSimulation.h
- Core/Simulation/OffSpecSimulation.cpp
- Core/Simulation/OffSpecSimulation.h
- Core/Simulation/SimElementUtils.h
- Core/Simulation/Simulation.cpp
- Core/Simulation/Simulation.h
- Core/Simulation/SpecularSimulation.cpp
- Core/Simulation/SpecularSimulation.h
- Tests/Functional/Core/CoreSpecial/BatchSimulation.cpp
- Tests/UnitTests/Core/Other/ThreadInfoTest.h
- auto/Wrap/doxygen_core.i
- auto/Wrap/libBornAgainCore.py
1. Iterator-based methods replaced by index-based methods in Simulation
2. Simulation elements moved down to leaf classes in Simulation hierarchy
Seems that part of Simulation functionality can be isolated in a separate hierarchy with a templated class
> Redmine issue 1917: removed simulation elements from Simulation class

- GUI/main/CMakeLists.txt
The following fix is necessary to ensure that the Boost installation as
found by CMake will be used, instead of the one that is installed in
/usr/include.
> Fix Boost include for GUI

- Core/Aggregate/InterferenceFunction2DParaCrystal.cpp
- Core/Aggregate/InterferenceFunctionRadialParaCrystal.cpp
- Core/Fitting/FitSuiteImpl.cpp
- Core/Fitting/FitSuiteObjects.h
- Core/Instrument/IntensityDataFunctions.cpp
- Core/Mask/Polygon.cpp
- Core/Material/MaterialBySLDImpl.h
- Core/Material/MaterialFactoryFuncs.h
- GUI/coregui/Models/BeamDistributionItem.cpp
- GUI/coregui/Models/DetectorItems.h
- GUI/coregui/Models/LayerRoughnessItems.cpp
- GUI/coregui/Views/FitWidgets/FitComparisonController.h
- GUI/coregui/Views/InstrumentWidgets/DetectorMaskDelegate.h
- GUI/coregui/Views/MaskWidgets/MaskUnitsConverter.cpp
- GUI/coregui/Views/MaskWidgets/PolygonView.cpp
- GUI/coregui/Views/SampleDesigner/DesignerHelper.cpp
- GUI/coregui/Views/SampleDesigner/DesignerHelper.h
- Tests/Functional/Python/PyCore/histogram2d.py
- Tests/Functional/Python/PyCore/mesocrystal1.py
- Tests/UnitTests/Core/DataStructure/IntensityDataFunctionsTest.h
Hi,
while working on the debian packaging (*slowly* getting there!) I discovered some common misspellings with lintian (a debian static package analysis tool). As far as I can tell, this doesn't change API so should be safe to apply.
Cheers
Mika
> Correct common typos discovered by lintian.

- Core/Fitting/FitObject.cpp
- Core/Fitting/FitObject.h
- Core/Instrument/IDetector.cpp
- Core/Instrument/IntensityDataFunctions.cpp
- Core/Instrument/IntensityDataFunctions.h
- auto/Wrap/libBornAgainCore.py
* Put intensities to zero in masked areas of simulated image to avoid negative amplitudes (because of detector resolution)
* Global function to convert user data to SimulationResult
> Refactoring in FitObject and IDetector

- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.h
In this pull request the following have been implemented:
1. A separate function to populate a single particle
2. Functions for populating various particle types (e.g. ParticleComposition, ParticleCoreShell, single particle) have been moved from RealSpaceBuilder.cpp to RealSpaceBuilderUtils.cpp
3. Function for populating ParticleDistribution has been implemented
**Note** - In order to view in the GUI the standard sample "Cylinders with size distribution", please change the TotalParticleDensity to a smaller value (e.g. 0.001). Otherwise the program takes an enormous amount of time to execute.
> GUI ParticleDistribution implementation

- GUI/coregui/Models/DataItem1DView.cpp
- GUI/coregui/Models/DataItem1DView.h
- GUI/coregui/Models/DataItemView.cpp
- GUI/coregui/Models/DataViewUtils.cpp
- GUI/coregui/Models/DataViewUtils.h
- GUI/coregui/Models/JobItem.cpp
- GUI/coregui/Models/JobModelFunctions.cpp
- GUI/coregui/Views/FitWidgets/FitComparisonWidget1D_New.cpp
- GUI/coregui/Views/FitWidgets/FitComparisonWidget1D_New.h
- GUI/coregui/Views/IntensityDataWidgets/Plot1D.cpp
- GUI/coregui/Views/IntensityDataWidgets/Plot1D.h
- GUI/coregui/Views/JobWidgets/JobResultsPresenter.cpp
- GUI/coregui/Views/SessionModelView.cpp
- GUI/coregui/Views/SpecularDataWidgets/Plot1DCanvas.cpp
- GUI/coregui/Views/SpecularDataWidgets/Plot1DCanvas.h
- GUI/coregui/Views/TestView.cpp
- Tests/UnitTests/GUI/TestDataItemViews.h
1. DataItem1DView does not change the state of DataItem anymore.
2. Connection of DataItem1DView to the instrument (for units conversion) is now done through finding parenting JobItem and using its InstrumentItem.
3. Unit conversion is done "on the fly", when graph data is requested, i.e. DataItem1DView does not store output data
> Redmine issue 2106: using DataItem1DView in fit view for 1D data

- cmake/bornagain/modules/SearchInstalledSoftware.cmake
boost-system and boost-regex both come from inter-dependencies of boost libraries. Should be removed from cmake files after all the other boost libs
> Returned regex in the list of dependencies

- cmake/bornagain/scripts/postinst.in
In the past commit, the postinst file was linking an "exec" folder that is not needed and was not being removed after "apt remove bornagain", now the postinst file is only linking the files needed.
> cleaner postinst file

- GUI/ba3d/ba3d/view/canvas.cpp
- GUI/ba3d/ba3d/view/canvas.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceCanvas.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceCanvas.h
Further changes implemented besides the above:
- Display busy cursor symbol during updateScene of 3D view
- Remove old function for displaying message in 3D view when no sample is selected. This was used when 3D view was inside TestView but now it seems unnecessary.
> 3D view Prevent update on simple item move on QGraphicsScene

- Core/Parametrization/ParameterPool.cpp
- Core/Parametrization/ParameterPool.h
This is related to investigation of bug #2129, which revealed that the error messages can be confusing.
> Amend error message during ParameterPool::setParameterValue

- GUI/ba3d/ba3d/model/geometry.cpp
- GUI/ba3d/ba3d/model/geometry.h
- GUI/ba3d/ba3d/model/geometry/column.cpp
- GUI/ba3d/ba3d/model/geometry/cuboctahedron.cpp
- GUI/ba3d/ba3d/model/geometry/dodecahedron.cpp
- GUI/ba3d/ba3d/model/geometry/icosahedron.cpp
- GUI/ba3d/ba3d/model/geometry/sphere.cpp
- GUI/ba3d/ba3d/model/geometry/truncbox.cpp
- GUI/ba3d/ba3d/model/geometry_inc.cpp
- GUI/ba3d/ba3d/model/geometry_inc.h
- GUI/ba3d/ba3d/model/particles.cpp
- GUI/ba3d/ba3d/model/particles.h
- The BaseShapes have been refactored such that the bottom of the objects lie in the z=0 plane during object creation and there remains no need for separately specifying the offset of the 3D particles (as done previously).
- This also fixes the error in the rotation of the 3D particle due to the non-zero offset parameter which was being specified previously.
> GUI3D Remove offset of particles during 3D particle construction

- GUI/ba3d/ba3d/model/particles.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.cpp
- Remove unnecessary comment from particles.cpp (was not removed previously).
- Do not display colour of the top layer when MultiLayer is selected in 3D view.
- Add a border width of 10 nm during calculation of lattice positions so that most of the particles are populated inside the layer boundaries.
> GUI3D Set border width for population of particles on a layer

- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant.h
- GUI/coregui/Views/ImportDataWidgets/CsvReader.cpp
- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.cpp
- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.h
- Before opening the ImportAssistant, a MessageBox asks: 'Data format not recognized, do you want to open the Import Assitant?'
- 'Export' button changed to 'Import'.
- 'Headers Row Number' removed from the GUI (The relevant code was only commented in case it turns out comfortable to have headers added in the future).
- Line numbers in the table widget match the line numbers in the file.
- If the last line is blank, it is ignored. If there are errors in the middle of files, users should pay more attention to the data they are trying to import. In addition, ignoring lines in the middle of the file would mess up the line numbering.
- Separators are automatically deduced from the file provided (Only from a subset of ascii characters: <SPACE> ; , : | <TAB> / _ \ ' " ).
> Corrections to CsvImportAssistant (http://apps.jcns.fz-juelich.de/redmine/issues/2137)

- GUI/coregui/Views/FitWidgets/GUIFitObserver.cpp
Have forgotten a check on last iteration in the case when the plotter is unlocked.
> Returned forgotten check on last iteration in canUpdatePlots

- GUI/ba3d/ba3d/view/canvas.cpp
- GUI/ba3d/ba3d/view/canvas.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceCanvas.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceCanvas.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceToolBar.cpp
- Allows the zoomLevel to be remembered when switching from side to top view or vice versa (reset on default view)
- Increase default layer display size in 3D view
- Change default camera position
> GUI3D Modification to zoom level for Top and Side View

- GUI/coregui/Views/FitWidgets/FitComparisonWidget1D.cpp
- GUI/coregui/Views/SpecularDataWidgets/SpecularPlot.cpp
This bug shows DataItemView vulnerability against changes in the model. In the future the linking mechanism should be somehow changed to be independent on SessionModel changes.
> Redmine issue 2171: fix for switching specular jobs

- Wrap/python/plot_utils.py
For the sake of back-compatibility
> Restoring default observer behaviour for old python projects

- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant.h
- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.cpp
- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.h
- Import of a 150x150 number array  
- Automatically guess separator without crashing
- "Separator" field updates table as expected.
- "Column" field updates table as expected.
- "From row" field updates table as expected.
- Does not crash when reading empty file.
- Does not crash when reading corrupted / binary file (shows rubbish on the table)
- *Read* 1200 x 1200 string array in 3 seconds
- *Import* 1200 x 1200 number array in 6 seconds (bad implementation, must be revisited)
- When hitting import an error message is shown if the data is not "good" (does not crash).
- Context menu works as expected (updates headers, updates table and updates controls in the bottom of the dialog).
- Import 1D works in two possible ways: a) setting 1 column as coordinate and 1 as intensity and then …
> Csv import assistant added

- Core/Instrument/AxisNames.h
- Core/Instrument/UnitConverter1D.cpp
- Core/Instrument/UnitConverter1D.h
- GUI/coregui/Models/DataItem.cpp
- GUI/coregui/Models/DataItem.h
- GUI/coregui/Models/DataViewUtils.cpp
- GUI/coregui/Models/DataViewUtils.h
- GUI/coregui/Models/IntensityDataItem.cpp
- GUI/coregui/Models/IntensityDataItem.h
- GUI/coregui/Models/JobItem.cpp
- GUI/coregui/Models/JobItemUtils.cpp
- GUI/coregui/Models/JobItemUtils.h
- GUI/coregui/Models/JobModelFunctions.cpp
- GUI/coregui/Models/JobModelFunctions.h
- GUI/coregui/Models/RealDataItem.cpp
- GUI/coregui/Models/RealDataItem.h
- GUI/coregui/Models/SpecularDataItem.cpp
- GUI/coregui/Models/SpecularDataItem.h
- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.cpp
- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.h
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorActions.cpp
- GUI/coregui/utils/ImportDataInfo.cpp
- GUI/coregui/utils/ImportDataInfo.h
- Tests/UnitTests/Core/Axes/UnitConverter1DTest.h
1. Revised implementation of `ImportDataInfo`
2. Native coordinates information in `RealDataItem`. It could be a good idea to replace these new properties with something like `ImportedDataItem` in order to remove any dimensional information from `RealDataItem`.
3. Minor refactoring in `JobItemUtils` and `DataViewUtils` to get rid of duplicating code (e.g. unit-name maps). In further pull-requests `DataViewUtils` namespace will be eliminated completely.
4. UnitConverter1D is now capable of accepting data in any units making sense for reflectometry instrument and known to BornAgain.
> To Redmine issue 2194: machinery for using and storing dimensional user data

- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/CsvImportAssistant.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/CsvImportAssistant.h
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/DataSelector.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/DataSelector.h
- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.cpp
- Corrupted files open as binary symbols (garbage).
- Empty files won't open in the importer --A dialog box is shown instead.
- Import button only active when the intensity column is selected
- If the data cannot be parsed as doubles, the importer is kept open after a failed import.
- If a PointwiseAxis exception is thrown, a dialog box is shown without making BA crash.
- On changing field separator the file is reloaded.
- Intensity and coordinate columns can be changed without needing to hit the reset button.
> CsvImportAssistant: Last Data Row Selector + Refactoring

- cmake/bornagain/modules/BornAgainCPack.cmake
This seems to be standard, at least for packages installed under Windows.
> Let CPACK_PACKAGE_VENDOR only show the corporation, not any subunit

- Tests/UnitTests/CMakeLists.txt
- Tests/UnitTests/GUI/CMakeLists.txt
- ThirdParty/common/gtest/CMakeLists.txt
- cmake/generic/modules/AddGTest.cmake
All changes are related only to unit test executables on Linux. They contain now hard coded path to own libBoprnAgain* and libgtest*. It is safe now, if LD_LIBRARY_PATH contain some prev BornAgain/libgtest installations.
> Fixed unit test crash when LD_LIBRARY contains own libgtest

- Core/Fitting/FitObjective.cpp
- Core/Fitting/FitObjective.h
- Core/Fitting/SimDataPair.cpp
- Core/Fitting/SimDataPair.h
- Core/StandardSamples/SimulationFactory.cpp
- Core/StandardSamples/StandardSimulations.cpp
- Core/StandardSamples/StandardSimulations.h
- Fit/RootAdapter/GSLLevenbergMarquardtMinimizer.cpp
- Fit/RootAdapter/GSLLevenbergMarquardtMinimizer.h
- Fit/RootAdapter/RootMinimizerAdapter.h
- GUI/coregui/Views/FitWidgets/FitObjectiveBuilder.cpp
- Tests/Functional/Fit/FitObjective/AdjustMinimizerPlan.cpp
- Tests/Functional/Fit/FitObjective/CMakeLists.txt
- Tests/Functional/Fit/FitObjective/FitObjectiveTestCases.cpp
- Tests/Functional/Fit/FitObjective/FitObjectiveTestCases.h
- Tests/Functional/Fit/FitObjective/FitObjectiveTestFactory.cpp
- Tests/Functional/Fit/FitObjective/FitPlanCases.cpp
- Tests/Functional/Fit/Minimizer/FunctionTestPlanCases.cpp
- Tests/Functional/Fit/Minimizer/FunctionTestPlanCases.h
- Tests/Functional/Fit/Minimizer/FunctionTestPlanFactory.cpp
- Tests/Functional/Fit/Minimizer/MinimizerTestCases.cpp
- Tests/Functional/Fit/Minimizer/MinimizerTestFactory.cpp
- Tests/Functional/TestMachinery/MinimizerTestPlan.cpp
- auto/Wrap/libBornAgainCore.py
+ Enable Fumili and Levenberg Marquardt in GUI
+ Disable possibility to have fit parameter limits for Levenberg Marquardt (ROOT wrapper around GSL is buggy)
+ Repair fit weights for multiple dataset scenario
> Forbid limits in fit parameters for Levenberg Marquardt algorithm

- GUI/coregui/Models/BeamDistributionItem.cpp
- GUI/coregui/Models/BeamItems.cpp
- GUI/coregui/Models/BeamItems.h
- GUI/coregui/Models/BeamWavelengthItem.cpp
- GUI/coregui/Models/BeamWavelengthItem.h
- GUI/coregui/Models/DepthProbeInstrumentItem.cpp
- GUI/coregui/Models/DepthProbeInstrumentItem.h
- GUI/coregui/Models/InstrumentItems.cpp
- GUI/coregui/Models/InstrumentItems.h
- GUI/coregui/Views/SimulationWidgets/SimulationSetupAssistant.cpp
1. Silent linking if instrument complies with real data
2. Prevent user from typing in out-of-range values for wavelength in instrument tab
3. Setting wavelength to a reasonable value in instrument tab if real data with q-coordinate is linked to an instrument.
4. Removed `InstrumentItem::setShape` method in favor of `InstrumentItem::updateToRealData`.
Some of the changes should be treated in a more generic fashion:
1. Replace `DoubleEditor` with `ScientificSpinBox`, which can handle limited values in a better way (`RealLimits::positive` in particular). In this PR it is used only for wavelength in specular instrument. 
2. Take care of setting proper limits to children if distribution item is changed. Now it is done only for `SymmetricDistributionItem::P_MEAN` (which should be actually …
> Fixes for issues #2235 and #2217

- Core/StandardSamples/SampleBuilderFactory.cpp
- Core/StandardSamples/SlicedCylindersBuilder.cpp
- Core/StandardSamples/SlicedCylindersBuilder.h
- Core/StandardSamples/StandardSimulations.cpp
- Tests/Functional/Core/CMakeLists.txt
- Tests/Functional/Core/SelfConsistenceTest/CMakeLists.txt
- Tests/Functional/Core/SelfConsistenceTest/SelfConsistenceTest.cpp
- Tests/Functional/Core/SelfConsistenceTest/SelfConsistenceTest.h
- Tests/Functional/Core/SelfConsistenceTest/SelfConsistenceTestService.cpp
- Tests/Functional/Core/SelfConsistenceTest/SelfConsistenceTestService.h
- Tests/Functional/Core/SelfConsistenceTest/main.cpp
- Tests/Functional/TestMachinery/StandardTestCatalogue.cpp
- Tests/Functional/TestMachinery/StandardTestCatalogue.h
- Tests/Functional/TestMachinery/StandardTestInfo.cpp
- Tests/Functional/TestMachinery/StandardTestInfo.h
- Tests/Functional/TestMachinery/StandardTestService.cpp
- Tests/Functional/TestMachinery/StandardTestService.h
- cmake/bornagain/scripts/BATesting.h.in
* a new type of functional tests `SelfConsistenceTest` introduced: it allows comparing several simulations without reference data.
* test for reflectometry data from a sliced sample was implemented as an example of such test
> Self-consistence test machinery and check for reflectometry on sliced sample

- Core/Multilayer/ScalarRTCoefficients.h
- Core/Multilayer/SpecularMatrix.cpp
- Core/Multilayer/SpecularMatrix.h
- Tests/UnitTests/Core/Fresnel/ScalarRTCoefficientsTest.cpp
- Tests/UnitTests/Core/Sample/RTTest.cpp
* The worst computation complexity is now linear on number of layers
* Direct (from top to bottom) computation of coefficients
* Computation uses only kz (instead of k) internally
Measured performance difference on specular simulations is negligible though.
> Refactoring in specular computation engine

- cmake/bornagain/modules/SearchInstalledSoftware.cmake
improve upon FindBoost(... REQUIRED), which does not work as expected
> CMake: terminate if a required Boost component is missing

- GUI/coregui/Views/PropertyEditor/CustomEditors.cpp
This PR resolves the issue no. [2321](http://apps.jcns.fz-juelich.de/redmine/issues/2321)
> Fix erroneous limits definition in fit parameter widget

- Core/Parametrization/RangedDistributions.cpp
- Core/Parametrization/RangedDistributions.h
- Tests/UnitTests/Core/Parameters/RangedDistributionTest.cpp
This PR allows setting zero to the `stddev` parameter when using `RangedDistribution` in specular scans. Hardly a user will do it intentionally, but it can happen during fitting.
> Fix specular simulation crash on delta-distributions

- GUI/coregui/Views/ImportDataWidgets/ImportDataUtils.cpp
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorActions.cpp
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorActions.h
This pull request addresses Feature 2319: BornAgain GUI is very convenient for viewing the experimental data. The only inconvenience is to import each single data file separately. For both, 2D and 1D data it should be allowed to select and import multiple files. 
http://apps.jcns.fz-juelich.de/redmine/issues/2319
> Import multiple data files at once

- Wrap/python/plot_utils.py
This is the first step towards resolving #2348.
Next steps:
- Document the new command.
- Agree on default color map (see http://apps.jcns.fz-juelich.de/doku/sc/tmp and https://matplotlib.org/tutorials/colors/colormaps.html)
- Recreate figures for online doc.
> Allow user choice of color map through command ba.set_map(name|cmap).

- Wrap/python/plot_utils.py
Reverts scgmlz/BornAgain#814
The new routine to set the color map breaks compatibility with the standard way of setting the color map through `matplotlib.rcParams['image.cmap']`. A better way to accomplish this functionality would be just adding a parameter `cmap = None` to the function `plot_simulation_result`.
> Revert "Allow user choice of color map through command ba.set_map(name|cmap)."

- Core/InputOutput/DataFormatUtils.cpp
- Core/InputOutput/DataFormatUtils.h
- Core/InputOutput/OutputDataReadFactory.cpp
- Core/InputOutput/OutputDataReadStrategy.cpp
- Core/InputOutput/OutputDataReader.cpp
- Core/InputOutput/OutputDataWriteFactory.cpp
- Core/InputOutput/OutputDataWriter.cpp
This pull request addresses Feature #2311 issue (http://apps.jcns.fz-juelich.de/redmine/issues/2311):
> Situation: [A user] brings *.dat file from experiment which contains simple 2D ascii map.
BornAgain refuses to read it. If we rename file to *.txt it reads it without problems.
> GUI allows for importing data matrix from text files with .txt extension. However, some MLZ instruments save this matrix in the text files with other extensions. For example, KWS3 saves matrix in the text files with extension .det.
> For an average GUI user it is quite some work to rename several tens of files to be able to load them in GUI.
> I think, this constraint should be relaxed. We should not determine the file type by extension.
In this pull request, the logic is changed: Files with extensions other …
> Treat evey file as ASCII unless it has a specific BA recognized extension.

- GUI/ba3d/ba3d/view/buffer.cpp
- GUI/ba3d/ba3d/view/buffer.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceCanvas.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceCanvas.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceToolBar.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceToolBar.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceWidget.cpp
- GUI/coregui/Views/SampleDesigner/SampleViewActions.cpp
- GUI/coregui/Views/SampleDesigner/SampleViewDocks.cpp
- GUI/coregui/Views/SampleDesigner/SampleViewDocks.h
This pull request implements Feature #2294 (http://apps.jcns.fz-juelich.de/redmine/issues/2294):
> Users are happy with 3D-Viewer and want to use images in their publications. For the moment, the only option to save the image of 3D view is to make a screenshot. Button "save image" is required for user convenience.
> 3DView: Provide button to save image

- Core/InputOutput/OutputDataReadStrategy.cpp
This reverts commit e1555e2026390e87f7e506685b84997d358dfa32.
If we advertise input units just as inverse nm, the import/labels/save become self-consistent.
> Revert "Translate q values from inv. angstroms into inv. nm in reflectometry import"

- Core/Simulation/DepthProbeSimulation.cpp
- Core/Simulation/DepthProbeSimulation.h
- Core/Simulation/GISASSimulation.cpp
- Core/Simulation/GISASSimulation.h
- Core/Simulation/OffSpecSimulation.cpp
- Core/Simulation/OffSpecSimulation.h
- Core/Simulation/Simulation2D.h
- auto/Wrap/libBornAgainCore.py
Previously it was returning the number of simulation elements for all simulations except for specular one. It is erroneous for off-spec and depth probe. In the case of GISAS it neglected masked areas.
> Provide proper behaviour for Simulation::intensityMapSize

- GUI/coregui/Models/SpecularBeamInclinationItem.cpp
- Tests/UnitTests/Core/Fresnel/SpecularSimulationTest.cpp
This Pull Request fixes bug 2370 (http://apps.jcns.fz-juelich.de/redmine/issues/2370):
> To reproduce:
> 
> 1. Instrument view: Choose the Specular Instrument; In the Beam Parameters section --> Inclination Angles [deg] --> Min = 0.0, Max = 91 (i.e. a non-sensible value).
> 2. Sample View: Create any Multilayer sample (I chose the example "Multilayer With Correlated Roughness").
> 3. Simulation View: Hit "Run Simulation".
> 4. Jobs View: The figure shows a plot "alpha_i [deg] vs Signal [a.u.]"; hit "Properties" on top of the plot; on the pane that appears at the right, change axes units to q-space or to radians.
> 5. Don't call it a crash; call it a shortcut for closing the application without being asked whether to save the changes :)
> 
> Possible ways to go (in no particular order):
> …
> Fix Bug 2370 [Reflectometry] - Crash for non-sensible values of theta.

- GUI/coregui/mainwindow/mainwindow.cpp
- This Pull Request implements Feature #2365 (http://apps.jcns.fz-juelich.de/redmine/issues/2365):
>This button gives access to the "Import 2D" and "Import 1D"
buttons, but also to the imported data display. Therefore,
"Data" is the more comprehensive name.
> GUI: rename 'Import' button to 'Data'

- GUI/coregui/Views/SampleDesigner/ILayerView.cpp
- GUI/coregui/Views/SampleDesigner/ILayerView.h
- GUI/coregui/Views/SampleDesigner/NodeEditorPort.cpp
- GUI/coregui/Views/SampleDesigner/NodeEditorPort.h
This Pull Request implements Feature #2285 - Name layers in GUI by their material name (http://apps.jcns.fz-juelich.de/redmine/issues/2285):
> The material name could also appear in the layer representation in the sample designer.
> Feature #2285 - Name layers in GUI by their material name

- Core/Fitting/FitObjective.cpp
- Core/Fitting/FitObjective.h
- Core/Fitting/ObjectiveMetric.cpp
- Core/Fitting/ObjectiveMetric.h
- Core/InputOutput/OutputDataReadStrategy.cpp
- Core/Instrument/ArrayUtils.h
- Core/Instrument/IntensityDataFunctions.cpp
- Core/Instrument/PyArrayImportUtils.cpp
- GUI/coregui/Views/FitWidgets/GUIFitObserver.cpp
- Tests/Functional/Fit/FitObjective/FitPlanCases.cpp
- Tests/Functional/GUI/GUISpecial/CsvImportAssistantPerformanceTest.cpp
- Tests/UnitTests/Core/DataStructure/ArrayUtilsTest.cpp
- Tests/UnitTests/Core/Fitting/ObjectiveMetricTest.cpp
- Tests/UnitTests/GUI/TestCsvImportAssistant.cpp
- Wrap/swig/extendCore.i
- Wrap/swig/ignores.i
- Wrap/swig/libBornAgainCore.i
- auto/Wrap/libBornAgainCore.py
Further steps to undertake:
1. Switch GUI to the new machinery
2. Extend default python plotter for reflectometry to show uncertainties
3. Write an example of usage
> Enable uncertainties and the new objective metrics

- Core/Simulation/OffSpecSimulation.cpp
- GUI/coregui/Models/InstrumentItems.cpp
This PR resolves [issue](http://apps.jcns.fz-juelich.de/redmine/issues/2329) and enables off-spec simulations with non-zero starting inclinations.
> Fix off-spec simulations with rectangular detector

- Wrap/python/plot_utils.py
To conform with standard scientific typesetting, units should _not_ be set in italics.
> PlotUtils: Units upright instead of italics.

- Core/Fitting/ObjectiveMetric.cpp
- Core/InputOutput/IntensityDataIOFactory.cpp
- Core/Instrument/SimulationResult.cpp
- Core/Instrument/SimulationResult.h
- GUI/coregui/Models/JobItemUtils.cpp
- GUI/coregui/Views/FitWidgets/GUIFitObserver.cpp
- Tests/Functional/Core/CoreSpecial/BatchSimulation.cpp
- Tests/Functional/Core/CoreSpecial/PolDWBAMagCylinders.cpp
- Tests/Functional/Core/CoreStandardTest/CoreStandardTest.cpp
- Tests/Functional/Core/SelfConsistenceTest/SelfConsistenceTest.cpp
- Tests/Functional/Fit/FitObjective/FitPlan.cpp
- Tests/Functional/GUI/GUIStandardTest/GUIStandardTest.cpp
- Tests/Functional/Python/PyPersistence/example_template.py
- Tests/Functional/Python/PyStandard/PyStandardTest.cpp
- Tests/UnitTests/Core/Fresnel/DepthProbeSimulationTest.cpp
- Tests/UnitTests/Core/Fresnel/SpecularSimulationTest.cpp
- Tests/UnitTests/Core/Other/SimulationResultTest.cpp
- Wrap/swig/libBornAgainCore.i
- auto/Wrap/libBornAgainCore.py
Leak summary
`
==79988==    definitely lost: 38,162 bytes in 988 blocks
==79988==    indirectly lost: 42,095,920 bytes in 3,206 blocks
`
After
`
==14538==    definitely lost: 20,978 bytes in 454 blocks
==14538==    indirectly lost: 2,184 bytes in 15 blocks
`
> Fix memory leakage both in GUI and PythonAPI

- Core/Multilayer/MultiLayer.cpp
- Core/StandardSamples/PlainMultiLayerBySLDBuilder.cpp
- Core/StandardSamples/PlainMultiLayerBySLDBuilder.h
- Tests/Functional/Core/CoreSpecial/CMakeLists.txt
- Tests/Functional/Core/CoreSpecial/CoreSpecialTestFactory.cpp
- Tests/Functional/Core/CoreSpecial/MultilayerPerformanceTest.cpp
- Tests/Functional/Core/CoreSpecial/MultilayerPerformanceTest.h
Before:
n_layers = 10,	 time = 4 ms
n_layers = 100,	 time = 64 ms
n_layers = 200,	 time = 349 ms
n_layers = 500,	 time = 4547 ms
n_layers = 1000,	 time = 34026 ms
After:
n_layers = 10,	 time = 4 ms
n_layers = 100,	 time = 28 ms
n_layers = 200,	 time = 52 ms
n_layers = 500,	 time = 210 ms
n_layers = 1000,	 time = 646 ms
> Fix O(n_layer^2) bug

- Doc/UserManual/Scattering.tex
Hi,
I think there is a small mistake in equation 1.22 of the UserManual (section 1.2.2, page 14 of Version 1.7.2).
It states:
|\vec r - \vec r'| = sqrt(r^2 - 2 \vec r \vec r')
but I think correct is:
|\vec r - \vec r'| = sqrt(r^2 + r'^2 - 2 \vec r \vec r')
In this pull request, this is corrected.
Cheers + thanks for the helpful Manual,
Mika
> UserManual/Scattering.tex: Correct eq. 1.22, add missing r'^2

- Doc/UserManual/Scattering.tex
Reverts scgmlz/BornAgain#890
Sorry for the confusion, but this is not an equation. The first two 'equation' signs denote approximate equality. In this case, the square of r' can be neglected, which is exactly what you want to achieve in the far field approximation.
> Revert "UserManual/Scattering.tex: Correct eq. 1.22, add missing r'^2"

- Core/Simulation/Simulation.cpp
Simulation::prepareSimulation() was called twice pretty much after each other in Simulation::runSimulation() and Simulation::runSingleSimulation( … ).
> remove redundant call to prepareSimulation()

- Core/Vector/Transform3D.cpp
- Core/Vector/Transform3D.h
- GUI/coregui/Models/Data1DViewItem.cpp
- GUI/coregui/Models/FTDecayFunctionItems.cpp
- GUI/coregui/Models/FTDistributionItems.cpp
- GUI/coregui/Models/InterferenceFunctionItems.cpp
- GUI/coregui/Models/JobItem.cpp
- GUI/coregui/Models/RectangularDetectorItem.cpp
- GUI/coregui/Models/SphericalDetectorItem.cpp
- GUI/coregui/Views/InfoWidgets/DistributionWidget.cpp
- GUI/coregui/Views/IntensityDataWidgets/ProjectionsPlot.cpp
- GUI/coregui/Views/IntensityDataWidgets/SaveProjectionsAssistant.cpp
- GUI/coregui/mainwindow/ProjectUtils.cpp
- GUI/coregui/mainwindow/SplashScreen.cpp
- GUI/coregui/mainwindow/actionmanager.cpp
- GUI/coregui/utils/MessageService.cpp
- Tests/UnitTests/Core/Detector/RectangularDetectorTest.cpp
- ThirdParty/GUI/qcustomplot/qcustomplot.cpp
- ThirdParty/GUI/qcustomplot/qcustomplot.h
- ThirdParty/GUI/qt-manhattan-style/stylehelper.cpp
+ Resolve warnings generated by Qt5.14 "deprecated" macro.
+ Decrease the number of compiler warnings under GCC 9.3.
The total number of warnings has dropped from 160 to 76. The remainings are mostly from SWIG.
> Qt warnings

- .appveyor.yml
- CMakeLists.txt
- Core/CMakeLists.txt
- cmake/bornagain/modules/BornAgainConfiguration.cmake
- cmake/bornagain/modules/SearchInstalledSoftware.cmake
+ Switch to MSVC2019, Qt5.14, and new boost-1.67 in Appveyor builds.
+ Attempt to switch to Python 3.8, then falling back to Python 3.7.
While switching to Python 3.8, Appveyor builds (and also local Windows builds) fail during the execution of the PyStandard test family. The reason is failed `import bornagain` because of "failed import of _libBornAgainCore.pyd". The reason is unclear and will be investigated later.
> Appveyor upgrade

- .appveyor.yml
- Tests/Functional/Python/PyCore/intensitydata.py
- Tests/Functional/Python/PyCore/intensitydata_io.py
- Tests/Functional/Python/PyCore/intensitydata_io_tiff.py
- Tests/Functional/Python/PyCore/mesocrystal1.py
- Tests/Functional/Python/PyCore/polmagcylinders1.py
- Tests/Functional/Python/PyCore/polmagcylinders2.py
- Tests/Functional/Python/PyCore/sliced_composition.py
- Tests/Functional/Python/PyCore/sliced_spheres.py
- Tests/Functional/Python/PyCore/transform_BoxComposition.py
- Tests/Functional/Python/PyCore/transform_CoreShellBox.py
- Tests/Functional/Python/PyCore/transform_box.py
- Tests/Functional/Python/PyCore/transform_cube.py
- Tests/Functional/Python/PyCore/utils.py
- Wrap/python/__init__.py.in
* paths in the PATH environment variable are via `add_dll_directory` enabled to load libs
* The import in some tests is switched to the more modern bornagain module
* AppVeyor is switched to Python 3.8
> Update Python 3.8 dll import and switch AppVeyor to it

- Tests/UnitTests/GUI/TestUpdateTimer.cpp
- Tests/UnitTests/Numeric/FormFactorSpecializationTest.cpp
- Tests/UnitTests/Numeric/FormFactorSymmetryTest.cpp
- Tests/UnitTests/Numeric/FormFactorTest.cpp
- Tests/UnitTests/Numeric/FormFactorTest.h
- Print q if a test fails
- Modify q set (add low-symmetry directions, rm intermediate magnitudes)
- Replace template mechanism by lambda function call
-  Resolve parameter initialization into explicit 4D loop
-  Remove one level of inheritance
-  Provide comments
-  Add tests for FullSpheroid
This resolves http://apps.jcns.fz-juelich.de/redmine/issues/2454
Replaces #951, which I could not reopen after forced push.
> Revise UnitTests/Numeric (replaces #951)

- .github/workflows/ba-linux.yml
- .github/workflows/ba-macos.yml
- .github/workflows/ba-windows.yml
- README.md
- cmake/bornagain/scripts/fix_apple_bundle.py
This finalizes efforts of @mganeva  and @rbeerwerth 
+ Implements GitHub actions for Windows, Mac, and Linux builds.
+ Provides parallel builds.
+ Triggered on push/pull into master and develop branches.
+ Ignores Documentation folder.
+ Support of CMake cache for all 3 platforms (build time 35 min -> 8 min)
+ Upload of functional test logs in the case of failure as build artifacts.
+ Generation and upload of *.dmg and *.exe installers as build artifacts.
Old Travis and Appveyor builds will be disabled after the merge. Configs for Travis and Appveyor I suggest to keep for a while.
> Enable GitHub build actions

- Core/Basics/ISingleton.h
Thread-safety is guaranteed in C++11.
No more need for a mutex lock.
> Simplify ISingleton

- Core/Multilayer/SpecularScalarStrategy.cpp
- Core/Multilayer/SpecularScalarStrategy.h
- Tests/UnitTests/Core/Sample/RTTest.cpp
This PR fixes an ugly use-after-free in RTTest.
Furthermore some cleanup of unused variables in the scalar Fresnel kernel is done and the use of indices is changed such that it is a bit easier readable and consistent with the upcoming polarized engine.
> Small changes in scalar Fresnel computation + Bugfix

- CMakeLists.txt
- Core/Basics/Complex.h
- Core/Computation/SpecularComputationTerm.cpp
- Core/Computation/SpecularComputationTerm.h
- Core/HardParticle/FormFactorPolyhedron.cpp
- Core/HardParticle/FormFactorTruncatedSpheroid.cpp
- Core/HardParticle/Ripples.cpp
- Core/Material/MaterialUtils.cpp
- Core/Multilayer/ISpecularStrategy.h
- Core/Multilayer/MatrixFresnelMap.cpp
- Core/Multilayer/ScalarFresnelMap.cpp
- Core/Multilayer/SpecularMagneticOldStrategy.cpp
- Core/Multilayer/SpecularMagneticStrategy.cpp
- Core/Multilayer/SpecularMagneticStrategy.h
- Core/Multilayer/SpecularScalarStrategy.h
- Core/RT/ILayerRTCoefficients.h
- Core/RT/MatrixRTCoefficients_v2.cpp
- Core/RT/MatrixRTCoefficients_v2.h
- Tests/UnitTests/Core/Axes/CVectorTest.cpp
This PR provides an enhanced numerical stability of the existing implementation of the polarized Fresnel computation. This method is unchanged and as described in the document theory/polarizedSpecular. 
The modification applied in the last commit is described in Section 4 of that document. 
With these changes, the numerical precision is enhanced for samples with more than a few layers as long as all the the layers are not too thick. Due to the rotation of the polarization there is still a significant loss of precision if the layer thickness becomes too large.
The first three commits do minor changes, also in preparation of the new polarized computational kernel, that will supersede this implementation. Even though this implementation will likely not be used in the future it still makes …
> Stabilized existing implementation of magnetic Fresnel computation

- Examples/python/utils/plot_intensity_data.py
- Examples/python/utils/plot_intensity_data_diff.py
This eliminates warnings, and thereby resolves #987.
No review needed. Will merge when tests pass.
> Python utils: replace obsolete histogram method getArray() by array()

- cmake/modules/BornAgainCPack.cmake
STGZ seems to be no longer supported by CMake.
We don't know what it is and why it was there in a first place.
This resolves http://apps.jcns.fz-juelich.de/redmine/issues/2216.
> CPack: remove STGZ

- Core/Multilayer/SpecularMagneticNewStrategy.cpp
- Core/Multilayer/SpecularMagneticStrategy.cpp
- Core/RT/MatrixRTCoefficients_v3.cpp
- Core/RT/MatrixRTCoefficients_v3.h
- Tests/GTestWrapper/google_test.h
- Tests/UnitTests/Core/Fresnel/MatrixRTCoefficients_v3Test.cpp
- Tests/UnitTests/Core/Fresnel/SpecularMagneticTest.cpp
This PR corrects the treatment of the case kz = 0 and its limit to be consistent with the scalar implementation.
The tests are corrected in accordance and a proper consistency check between the scalar and polarized computation is performed.
The case k = 0 is not handled correctly in the previous implementation, and is disabled now.
> Correctly handle kz = 0 and kz -> 0 for polarized computations

- GUI/coregui/mainwindow/mainwindow.cpp
- GUI/coregui/mainwindow/mainwindow.h
Remove any reference to Manhattan::FancyTabWidget.
Note that there are two points where high dpi devices might need special treatment. This has to be tested. The relevant points are marked with ```// TODO: check with High-DPI devices!```
> Remove fancy tab widget

- CHANGELOG
- Core/Scan/QSpecScan.cpp
- Core/Scan/QSpecScan.h
- Examples/fit56_SpecularAdvanced/Pt_layer_fit.py
- Tests/UnitTests/Core/Fresnel/SpecularScanTest.cpp
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainCore_wrap.cpp
This PR adds API support for an offset in Q to QSpecScan. This solves http://apps.jcns.fz-juelich.de/redmine/issues/2496 and eliminates the necessity to work around this missing feature as described in https://www.bornagainproject.org/documentation/examples/fitting/extended/reflectometry-pt-layer/
> Add Q-Offset to QSpecScan

- GUI/coregui/Models/AxesItems.cpp
- GUI/coregui/Models/AxesItems.h
- GUI/coregui/Models/BeamDistributionItem.cpp
- GUI/coregui/Models/BeamItems.cpp
- GUI/coregui/Models/Data1DViewItem.cpp
- GUI/coregui/Models/Data1DViewItem.h
- GUI/coregui/Models/DataItem.h
- GUI/coregui/Models/DepthProbeInstrumentItem.cpp
- GUI/coregui/Models/DomainObjectBuilder.cpp
- GUI/coregui/Models/DomainSimulationBuilder.cpp
- GUI/coregui/Models/FitSuiteItem.cpp
- GUI/coregui/Models/InstrumentItems.cpp
- GUI/coregui/Models/IntensityDataItem.cpp
- GUI/coregui/Models/IntensityDataItem.h
- GUI/coregui/Models/ParticleItem.cpp
- GUI/coregui/Models/PointwiseAxisItem.cpp
- GUI/coregui/Models/RectangularDetectorItem.cpp
- GUI/coregui/Models/RectangularDetectorItem.h
- GUI/coregui/Models/SpecularBeamInclinationItem.cpp
- GUI/coregui/Models/SpecularDataItem.cpp
- GUI/coregui/Models/SpecularDataItem.h
- GUI/coregui/Models/SphericalDetectorItem.cpp
- GUI/coregui/Models/SphericalDetectorItem.h
- GUI/coregui/Models/TransformFromDomain.cpp
- GUI/coregui/Views/InstrumentWidgets/DetectorMaskDelegate.cpp
- GUI/coregui/Views/InstrumentWidgets/RectangularDetectorEditor.cpp
- GUI/coregui/Views/InstrumentWidgets/SphericalDetectorEditor.cpp
- Tests/UnitTests/GUI/TestAxesItems.cpp
- Few getter/setters for axes related properties.
- Replace getItem with type-safe item<T> (where it was easy to do).
- Number of `getItem()` usages decreased from 385 to 292.
> Decrease get item usage

- GUI/coregui/Models/BeamItems.cpp
- GUI/coregui/Models/BeamItems.h
- GUI/coregui/Models/Data1DViewItem.cpp
- GUI/coregui/Models/DepthProbeInstrumentItem.cpp
- GUI/coregui/Models/DetectorItems.cpp
- GUI/coregui/Models/InstrumentItems.cpp
- GUI/coregui/Models/InstrumentItems.h
- GUI/coregui/Models/IntensityDataItem.cpp
- GUI/coregui/Models/MaterialItem.cpp
- GUI/coregui/Models/MesoCrystalItem.cpp
- GUI/coregui/Models/MultiLayerItem.cpp
- GUI/coregui/Models/ParticleCompositionItem.cpp
- GUI/coregui/Models/ParticleCoreShellItem.cpp
- GUI/coregui/Models/ParticleItem.cpp
- GUI/coregui/Models/RectangularDetectorItem.cpp
- GUI/coregui/Models/SessionItem.cpp
- GUI/coregui/Models/SessionItem.h
- GUI/coregui/Models/SpecularDataItem.cpp
- GUI/coregui/Models/SphericalDetectorItem.cpp
Provides the possibility to add a single property item via the type-safe addProperty<> method.
The final task is to replace addGroupProperty completely with a type-safe mechanism.
> Add single property items (i.e. VectorItem) via type safe mechanism

- Examples/fit55_SpecularIntro/FitSpecularBasics.py
The `ba_fitmonitor` was called without having been imported. This PR resolves this.
> Added fitmonitor import

- gui2/dataloader/importfilewidget.cpp
Often reflectometry files are given the extension `.dat`. I have added this to the gui2 import menu as a quality of life improvement.
> add support for .dat file

- GUI/coregui/CMakeLists.txt
- GUI/coregui/Views/SampleDesigner/LayerView.cpp
MVVM dependency with current MAC pipeline causes runtime error on MAC (missing library when installing with one of the artifacts). This may be the case as well on Windows/Linux, but I didn't test it.
Since so far only one minor call is used from MVVM, this dependency has been removed.
Seems important for upcoming release 1.19.0
> Remove dependency from MVVM lib
