- Core/Export/ExportToPython.cpp
- Core/Fitting/FitObject.cpp
- Core/Fitting/FitObject.h
- Core/Instrument/DetectorMask.cpp
- Core/Instrument/DetectorMask.h
- Core/Instrument/IDetector2D.cpp
- Core/Instrument/IDetector2D.h
- Core/Instrument/RegionOfInterest.cpp
- Core/Instrument/RegionOfInterest.h
- Core/Instrument/SimulationArea.cpp
- Core/Instrument/SimulationArea.h
- GUI/coregui/Models/TransformFromDomain.cpp
- Tests/Functional/Fit/RectDetectorFitTest.cpp
- Tests/UnitTests/Core/3/DetectorMaskTest.h
- Tests/UnitTests/Core/3/SimulationAreaTest.h
- Tests/UnitTests/Core/3/SphericalDetectorTest.h
- auto/Wrap/libBornAgainCore.py
- dev-tools/log/perf_history.txt
More efficient simulation area iterator in the presence of region of interest. This concludes http://apps.jcns.fz-juelich.de/redmine/issues/1487.
> Masks and roi

- Core/Fitting/FitObject.cpp
- Core/Fitting/FitObject.h
- Core/Instrument/DetectorFunctions.cpp
- Core/Instrument/DetectorFunctions.h
- GUI/coregui/Models/DetectorItems.cpp
- GUI/coregui/Models/DetectorItems.h
- GUI/coregui/Models/DomainFittingBuilder.cpp
- GUI/coregui/Models/DomainSimulationBuilder.cpp
- GUI/coregui/Models/JobItem.cpp
- GUI/coregui/Models/JobItem.h
- GUI/coregui/Models/JobItemHelper.cpp
- GUI/coregui/Models/JobItemHelper.h
- GUI/coregui/Models/JobModel.cpp
- GUI/coregui/Models/JobModel.h
- GUI/coregui/Models/JobModelFunctions.cpp
- GUI/coregui/Models/JobModelFunctions.h
- GUI/coregui/Models/JobQueueData.cpp
- GUI/coregui/Models/ModelMapper.h
- GUI/coregui/Models/ParameterTreeBuilder.cpp
- GUI/coregui/Models/RealDataItem.cpp
- GUI/coregui/Models/TransformToDomain.cpp
- GUI/coregui/Models/TransformToDomain.h
- GUI/coregui/Views/FitWidgets/FitComparisonWidget.cpp
- GUI/coregui/Views/InstrumentWidgets/DetectorMaskDelegate.cpp
- GUI/coregui/Views/JobWidgets/ParameterTuningWidget.cpp
Masks and ROI are propagated from ImportDataView to the GUI fit job. Now it should be possible to fit small areas of large detectors (with masks also), as in FitGALAXI example. This concludes, in general http://apps.jcns.fz-juelich.de/redmine/issues/1488. Lots of validation is required.
> Fit from gui

- Core/Basics/BornAgainNamespace.h
- Core/Instrument/Beam.cpp
- Core/StandardSamples/StandardSimulations.cpp
- Examples/python/simulation/ex05_BeamAndDetector/BeamDivergence.py
- GUI/coregui/Models/BeamItem.cpp
- GUI/coregui/Models/DomainFittingBuilder.cpp
- GUI/coregui/Models/LayerItem.cpp
- GUI/coregui/Models/ModelPath.cpp
- GUI/coregui/Models/ModelPath.h
- GUI/coregui/Models/MultiLayerItem.cpp
- GUI/coregui/Models/ParameterTranslators.cpp
- GUI/coregui/Models/ParameterTranslators.h
- GUI/coregui/Models/TransformFromDomain.cpp
- GUI/coregui/Models/TransformToDomain.cpp
- auto/Wrap/libBornAgainCore.py
Fixed the parameters that are already available in the core. Also created two new issues because this mechanism will have to be refactored in the next sprint.
> Fit parameter names

- Core/Aggregate/InterferenceFunction2DLattice.cpp
- Core/Aggregate/InterferenceFunction2DLattice.h
- GUI/coregui/Models/ParameterTranslators.cpp
- GUI/coregui/Models/ParameterTranslators.h
- GUI/coregui/Views/JobWidgets/JobOutputDataWidget.cpp
- Tests/Functional/CMakeLists.txt
- Tests/Functional/GUI/GUITranslationTest/GUITranslationTest.cpp
- Tests/Functional/GUI/GUITranslationTest/main.cpp
InterferenceFunction2D fitting is working from GUI
> Parameter translation

- Core/Aggregate/ILayout.h
> Improved class comment to explain need for ILayout

- .github/ISSUE_TEMPLATE.md
Suggestion for a Github template for a new issue.
> Github template for a new issue.

- cmake/generic/modules/FindBoost.cmake
Otherwise build will fail under latest Debian/testing.
> Add patched FindBoost.cmake, needed when CMake-3.6 hits Boost-1.62

- Core/Aggregate/ParticleLayout.cpp
- Core/Parametrization/Distributions.cpp
- Core/Parametrization/Distributions.h
- Core/Parametrization/ParameterDistribution.cpp
- Core/Parametrization/ParameterPool.cpp
- Core/Parametrization/ParameterPool.h
- Core/Parametrization/ParameterSample.h
- Core/Particle/ParticleCoreShell.cpp
- Core/Particle/ParticleCoreShell.h
- Core/Particle/ParticleDistribution.cpp
- Core/Particle/ParticleDistribution.h
- Core/SoftParticle/FormFactorSphereLogNormalRadius.cpp
- Examples/python/simulation/ex03_InterferenceFunctions/Interference2DLatticeSumOfRotated.py
- GUI/coregui/Views/InfoWidgets/DistributionWidget.cpp
- Tests/UnitTests/Core/5/DistributionsTest.h
- auto/Wrap/libBornAgainCore.py
While working towards understanding of ParticleDistribution::generateParticles():
Comments, code layout, move small code fragments around.
> Light refactoring of parameter and particle distribution machinery

- Core/Basics/ICloneable.h
- Core/Binning/ConstKBinAxis.h
- Core/Binning/SimulationElement.cpp
- Core/Binning/SimulationElement.h
- Core/Binning/VariableBinAxis.h
- Core/HardParticle/FormFactorPolyhedron.cpp
- Core/HardParticle/FormFactorRipple1.cpp
- Core/InputOutput/OutputDataWriteStrategy.cpp
- Core/Instrument/RectangularDetector.cpp
- Core/Material/HomogeneousMagneticMaterial.h
- Core/Multilayer/SpecularMagnetic.cpp
- Core/Particle/IParticle.cpp
- Core/Particle/ParticleDistribution.h
- Core/Scattering/Rotations.cpp
- Core/Scattering/Rotations.h
- Core/Vector/BasicVector3D.cpp
- Core/Vector/BasicVector3D.h
- Doc/UserManual/fig/ff2/sim_Dodecahedron_asy.py
- Doc/UserManual/fig/ff2/sim_Icosahedron_asy.py
- Wrap/swig/ignores.i
- auto/Wrap/doxygen_core.i
- auto/Wrap/doxygen_fit.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainFit.py
- auto/Wrap/libBornAgainFit_wrap.cpp
Replacement for pull request #88
> Global functions

- Core/InputOutput/TiffHandler.cpp
The Desy TIFF files use IEEE float sample format. TiffHandler silently assumed that samples are uint32. Now supports uint32 / int32 / float.
Fixes redmine issues 1667 + 1668.
> Issues 1667/8: added float sample support to TiffHandler

- Examples/python/utils/plot_intensity_data.py
- Examples/python/utils/plot_intensity_data_diff.py
plot_intensity_data_diff.py:
- repair for Python 2.7.12+
- print message and exit if data sets coincide
plot_intensity_data.py:
- optional argument to fix intensity scale.
> plot utilities: repair and improve

- Core/Multilayer/SpecularMatrix.cpp
- Tests/UnitTests/Core/Sample/RTTest.h
This resolves issue 1732, and yields a measurable gain in speed.
> Optimize RT computation, mostly by using bisection

- Core/Parametrization/INode.cpp
- Core/Parametrization/IParameterized.cpp
- Core/Parametrization/IParameterized.h
- Core/Parametrization/ParameterPool.cpp
- Core/Parametrization/ParameterPool.h
- Core/Parametrization/RealParameter.cpp
- Core/Parametrization/RealParameter.h
- GUI/coregui/Models/ParticleDistributionItem.cpp
- Tests/Functional/GUI/GUITranslationTest/GUITranslationTest.cpp
- Tests/UnitTests/Core/Parameters/ParameterPoolTest.h
- Wrap/swig/ignores.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainCore_wrap.h
* unit tests for ParameterPool reenabled and revised
* bug in ParameterPool::clone fixed
* unused callback and name removed
> Parameter pool cleanup

- Doc/UserManual/Assemblies.tex
> Remove incorrect note about particle SLD.

- Core/Particle/MesoCrystal.cpp
- Core/Particle/MesoCrystal.h
- Core/Particle/ParticleCoreShell.cpp
Nothing needed to be done, since they all seem to be propagated. Only some minor code reordering and an extra comment.
> Verified propagation of rotations/translations across IParticle hierarchy

- Core/HardParticle/FormFactorAnisoPyramid.cpp
- Core/HardParticle/FormFactorBox.cpp
- Core/HardParticle/FormFactorCone.cpp
- Core/HardParticle/FormFactorCone6.cpp
- Core/HardParticle/FormFactorCuboctahedron.cpp
- Core/HardParticle/FormFactorCylinder.cpp
- Core/HardParticle/FormFactorEllipsoidalCylinder.cpp
- Core/HardParticle/FormFactorFullSphere.h
- Core/HardParticle/FormFactorFullSpheroid.cpp
- Core/HardParticle/FormFactorLongBoxGauss.cpp
- Core/HardParticle/FormFactorLongBoxLorentz.cpp
- Core/HardParticle/FormFactorPrism3.cpp
- Core/HardParticle/FormFactorPrism6.cpp
- Core/HardParticle/FormFactorPyramid.cpp
- Core/HardParticle/FormFactorTetrahedron.cpp
- Core/HardParticle/FormFactorTrivial.h
- Core/HardParticle/FormFactorTruncatedSphere.cpp
- Core/HardParticle/FormFactorTruncatedSpheroid.cpp
- Core/Scattering/IFormFactor.cpp
- Core/Scattering/IFormFactor.h
- Core/Scattering/IFormFactorBorn.cpp
- Core/Scattering/IFormFactorBorn.h
- auto/Wrap/doxygen_core.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainCore_wrap.h
Removed some code duplication and prepared the code for implementing a generic slicing form factor that would be constructed if the form factor does not know how to slice itself.
> Small refactoring

- GUI/coregui/Models/ParameterTreeUtils.cpp
- GUI/coregui/Views/IntensityDataWidgets/IntensityDataCanvas.cpp
- GUI/coregui/Views/IntensityDataWidgets/IntensityDataCanvas.h
This resolves http://apps.jcns.fz-juelich.de/redmine/issues/1683
> Interpolation flag and gradient are saved in global config

- GUI/coregui/mainwindow/projectmanager.cpp
> Prevent deletion handling during closing of empty project

- GUI/ba3d/ba3d/model/object.cpp
- GUI/ba3d/ba3d/view/program.cpp
- GUI/ba3d/demo/demo_model.cpp
- GUI/ba3d/demo/demo_model.h
- GUI/ba3d/demo/main.cpp
- GUI/ba3d/demo/mainwin.cpp
- GUI/ba3d/demo/mainwin.h
OpenGL/GPU shading gives visually different results ("bleached") on OSX. That needs future investigation. For now (demo) the colours have been #ifdef'd to suit OSX. There are a few small adjustments as well.
> demo: better colours on OSX

- Core/Instrument/SampleProvider.cpp
- Core/Instrument/SampleProvider.h
- Core/Lattice/Lattice2D.cpp
- Core/Lattice/Lattice2D.h
- Examples/python/fitting/ex03_FitSpheresInHexLattice/FitSpheresInHexLattice.py
- Examples/python/fitting/ex03_FitSpheresInHexLattice/FitSpheresInHexLattice_builder.py
- auto/Wrap/libBornAgainCore.py
to fix bug in unitCellArea() calculations
> Refactoring in Lattice2D

- GUI/coregui/Views/MaskWidgets/IShape2DView.cpp
- GUI/coregui/Views/MaskWidgets/MaskEditorCanvas.cpp
Rotation of intensity data will also remove masks, if exist
> Intensity rotation

- .appveyor.yml
- Core/Tools/SysUtils.cpp
- Core/Tools/SysUtils.h
- Tests/Functional/CMakeLists.txt
- Tests/Functional/Core/CoreStandardTest/CoreStandardTest.cpp
- Tests/Functional/Python/CMakeLists.txt
- Tests/Functional/Python/PyEmbedded/CMakeLists.txt
- Tests/Functional/Python/PyEmbedded/PyEmbeddedTestFactory.cpp
- Tests/Functional/Python/PyEmbedded/PyEmbeddedUtils.cpp
- Tests/Functional/Python/PyEmbedded/PyEmbeddedUtils.h
- Tests/Functional/Python/PyEmbedded/TestCases.cpp
- Tests/Functional/Python/PyEmbedded/TestCases.h
- Tests/Functional/Python/PyStandard/PyStandardTest.cpp
- Tests/Functional/TestMachinery/TestUtils.cpp
- Tests/UnitTests/GUI/TestIntensityDataItem.h
- cmake/bornagain/modules/BornAgainConfiguration.cmake
- cmake/bornagain/scripts/BABuild.h.in
- cmake/generic/modules/FindNumpy.cmake
* More PyEmbedded tests
* Finaly everythings works on buildserver/travis/appveyer
> Continuing with PyEmbedded tests

- .appveyor.yml
- GUI/coregui/Models/ComponentProxyStrategy.cpp
- GUI/coregui/Models/SessionModelDelegate.cpp
- GUI/coregui/Models/SessionModelDelegate.h
- GUI/coregui/Views/PropertyEditor/ComponentFlatView.cpp
- GUI/coregui/Views/PropertyEditor/ComponentFlatView.h
- GUI/coregui/Views/PropertyEditor/ComponentUtils.cpp
- GUI/coregui/Views/PropertyEditor/ComponentUtils.h
- GUI/coregui/Views/PropertyEditor/CustomEditors.cpp
- GUI/coregui/Views/PropertyEditor/CustomEditors.h
- GUI/coregui/Views/PropertyEditor/PropertyEditorFactory.cpp
- GUI/coregui/Views/PropertyEditor/PropertyEditorFactory.h
- GUI/coregui/Views/PropertyEditor/PropertyWidgetItem.cpp
- GUI/coregui/Views/PropertyEditor/PropertyWidgetItem.h
- GUI/coregui/Views/PropertyEditor/TestComponentView.cpp
- GUI/coregui/Views/PropertyEditor/TestComponentView.h
- GUI/coregui/utils/LayoutUtils.cpp
- GUI/coregui/utils/LayoutUtils.h
- Tests/UnitTests/GUI/TestComponentUtils.h
- Tests/UnitTests/GUI/TestGUI.cpp
* ComponentFlatView editor is a replacement of ComponentEditor in BROWSER_GROUPBOX mode
* Editor is located in TestView
* Some tuning in custom delegates still required (bool, string, etc)
* Almost ready for qtpropertybrowser framework removal
For the moment the GUI still using old ComponentEditor.
> Working prototype of ComponentFlatView

- GUI/coregui/Views/ImportDataWidgets/LinkInstrumentManager.cpp
- GUI/coregui/Views/PropertyEditor/PropertyEditorFactory.cpp
* [GUI: using tab after entering parameter value puts back the old value](http://apps.jcns.fz-juelich.de/redmine/issues/1922)
* [GUI: crash in import data view when linking to instrument](http://apps.jcns.fz-juelich.de/redmine/issues/1891)
> Two bugs fixed

- GUI/coregui/Views/PropertyEditor/ComponentFlatView.cpp
- GUI/coregui/Views/SimulationView.cpp
- GUI/coregui/Views/SimulationView.h
- GUI/coregui/Views/WelcomeView.cpp
- GUI/coregui/Views/WelcomeView.h
- GUI/coregui/mainwindow/mainwindow.cpp
- GUI/coregui/mainwindow/mainwindow.h
- GUI/coregui/utils/LayoutUtils.cpp
- GUI/coregui/utils/LayoutUtils.h
- GUI/coregui/utils/StyleUtils.cpp
- GUI/coregui/utils/StyleUtils.h
- Tests/UnitTests/GUI/TestSaveService.h
Was triggered by ["bug"](http://apps.jcns.fz-juelich.de/redmine/issues/1898).
* spaghetti code extracted in few functions
* WelcomeView now updates itself (no mainwindow involved).
> Refactoring in WelcomeView

- Core/Instrument/GaussianBeamFormFactor.cpp
- Core/Instrument/GaussianBeamFormFactor.h
- Core/Instrument/IBeamFormFactor.cpp
- Core/Instrument/IBeamFormFactor.h
- Core/Instrument/SquareBeamFormFactor.cpp
- Core/Instrument/SquareBeamFormFactor.h
- Core/Multilayer/MultiLayer.cpp
- Core/Multilayer/MultiLayer.h
- Core/Tools/MathFunctions.cpp
- Core/Tools/MathFunctions.h
- Tests/UnitTests/Core/Other/BeamFootprintTest.h
- Tests/UnitTests/Core/Other/testlist.h
- Tests/UnitTests/Core/Sample/MultiLayerTest.h
- auto/Wrap/doxygen_core.i
- auto/Wrap/libBornAgainCore.py
> Redmine issue 1931: Footprint correction for specular simulation

- GUI/coregui/Models/AxesItems.cpp
- GUI/coregui/Models/AxesItems.h
- GUI/coregui/Models/DomainSimulationBuilder.cpp
- GUI/coregui/Models/InstrumentItems.cpp
- GUI/coregui/Models/InstrumentItems.h
- GUI/coregui/Models/InstrumentModel.cpp
- GUI/coregui/Models/InstrumentModel.h
- GUI/coregui/Models/JobItem.cpp
- GUI/coregui/Models/JobItem.h
- GUI/coregui/Models/JobItemUtils.cpp
- GUI/coregui/Models/JobItemUtils.h
- GUI/coregui/Models/JobModel.cpp
- GUI/coregui/Models/JobModelFunctions.cpp
- GUI/coregui/Models/RealDataItem.cpp
- GUI/coregui/Models/RealDataItem.h
- GUI/coregui/Models/TransformToDomain.cpp
- GUI/coregui/Models/TransformToDomain.h
- GUI/coregui/Views/ImportDataWidgets/LinkInstrumentManager.cpp
- GUI/coregui/Views/InstrumentWidgets/OffSpecBeamEditor.cpp
- Tests/Functional/GUI/GUISpecial/GUIPerformanceTest.cpp
- Tests/Functional/GUI/GUISpecial/GUISaveLoadProject.cpp
* OffSpec simulation can be run from GUI and generates some results
* OffSpec axes units are still wrong
* Refactoring in OffSpecInstrumentEditor is required (beam parameters etc)
> OffSpec instrument in GUI implemented

- GUI/coregui/Models/ApplicationModels.cpp
- GUI/coregui/Models/GUIObjectBuilder.cpp
- GUI/coregui/Models/GroupInfoCatalogue.cpp
- GUI/coregui/Models/ItemCatalogue.cpp
- GUI/coregui/Models/MaterialDataItems.cpp
- GUI/coregui/Models/MaterialDataItems.h
- GUI/coregui/Models/MaterialItem.cpp
- GUI/coregui/Models/MaterialItem.h
- GUI/coregui/Models/MaterialModel.cpp
- GUI/coregui/Models/MaterialModel.h
- GUI/coregui/Models/MaterialPropertyController.cpp
- GUI/coregui/Models/SessionDecorationModel.cpp
- GUI/coregui/Models/item_constants.h
- GUI/coregui/Views/MaterialEditor/MaterialEditor.cpp
- GUI/coregui/Views/MaterialEditor/MaterialEditorToolBar.cpp
- GUI/coregui/Views/MaterialEditor/MaterialItemUtils.cpp
- GUI/coregui/Views/PropertyEditor/ComponentUtils.cpp
- GUI/coregui/Views/PropertyEditor/TestComponentView.cpp
- Tests/UnitTests/GUI/TestMaterialModel.h
- Tests/UnitTests/GUI/TestMaterialPropertyController.h
* SLD materials from Domain to GUI and back are implemented
> SLD materials in GUI

- Core/StandardSamples/StandardSimulations.h
- GUI/coregui/Models/ApplicationModels.cpp
- GUI/coregui/Models/GUIDomainSampleVisitor.cpp
- GUI/coregui/Models/GUIDomainSampleVisitor.h
- GUI/coregui/Models/GUIExamplesFactory.cpp
- GUI/coregui/Models/GUIObjectBuilder.cpp
- GUI/coregui/Models/GUIObjectBuilder.h
- GUI/coregui/Models/InstrumentItems.cpp
- GUI/coregui/Models/TransformFromDomain.cpp
- GUI/coregui/Models/TransformFromDomain.h
- GUI/coregui/Views/PropertyEditor/TestComponentView.cpp
- GUI/coregui/mainwindow/PyImportAssistant.cpp
- Tests/Functional/GUI/GUISpecial/GUIPerformanceTest.cpp
- Tests/Functional/GUI/GUISpecial/GUISaveLoadProject.cpp
- Tests/Functional/GUI/GUISpecial/GUITranslationTest.cpp
- Tests/Functional/GUI/GUIStandardTest/CMakeLists.txt
- Tests/Functional/GUI/GUIStandardTest/GUIStandardTest.cpp
- Tests/UnitTests/GUI/TestAxesItems.h
- Tests/UnitTests/GUI/TestGUI.cpp
- Tests/UnitTests/GUI/TestLayerRoughnessItems.h
- Tests/UnitTests/GUI/TestParaCrystalItems.h
- Tests/UnitTests/GUI/TestParticleDistributionItem.h
* Now functional test OffSpecularResonator is running in all three domains
* OffSpec instrument beam divergence is not yet transformed
> OffSpecIntrument from domain to GUI

- GUI/coregui/Models/InstrumentItems.cpp
> Fixed background fitting issue

- GUI/ba3d/ba3d/view/canvas.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.h
- GUI/coregui/Views/RealSpaceWidgets/TransformTo3D.cpp
2D Interference lattices implemented - basic, hexagonal, square.
Added more 3D particles. Some of the 3D particles are not of correct shape (need to be fixed). Ripple1, Ripple2 and Dot Particle shapes have not yet been implemented.
> GUI 3D - Implemented 2D Interference lattices and Particle Shapes

- GUI/ba3d/ba3d/model/geometry.h
- GUI/ba3d/ba3d/model/geometry/column.cpp
- GUI/ba3d/ba3d/model/geometry/cuboctahedron.cpp
- GUI/ba3d/ba3d/model/particles.cpp
- GUI/ba3d/ba3d/view/canvas.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.cpp
- GUI/coregui/Views/RealSpaceWidgets/TransformTo3D.cpp
Note: Dot, Ripple1 and Ripple2 shapes not yet implemented.
> Modify BaseShapes for correct 3D visualization of particles in GUI

- Core/DecoratedFormFactor/IFormFactorDecorator.h
- GUI/ba3d/ba3d/model/particles.cpp
- GUI/ba3d/ba3d/shaders/fragment_shader.frag
- GUI/ba3d/ba3d/view/canvas.cpp
- GUI/coregui/Models/MaterialPropertyController.cpp
- GUI/coregui/Views/PropertyEditor/ComponentTreeView.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.h
- GUI/coregui/Views/RealSpaceWidgets/TransformTo3D.cpp
- GUI/coregui/Views/RealSpaceWidgets/TransformTo3D.h
- Tests/UnitTests/GUI/TestMaterialPropertyController.h
Temporarily in  files MaterialPropertyController and TestMaterialPropertyController the connection for propagating signal (dataChanged and rowRemoval) between original material model and the material property's model has been disabled.
> GUI ParticleComposition implementation

- GUI/coregui/Models/ItemFactory.cpp
- GUI/coregui/Models/LayerItem.cpp
- GUI/coregui/Models/LayerItem.h
- GUI/coregui/Models/MultiLayerItem.cpp
- GUI/coregui/Models/item_constants.h
- Tests/UnitTests/GUI/TestGUI.cpp
- Tests/UnitTests/GUI/TestMapperForItem.h
- Tests/UnitTests/GUI/TestMultiLayerItem.h
See http://apps.jcns.fz-juelich.de/redmine/issues/2092
> Fixed issue 2092 with top level thickness

- Core/Fitting/FitObjective.cpp
- Core/Fitting/FitObjective.h
- Core/Fitting/SimDataPair.cpp
- Core/Fitting/SimDataPair.h
- Examples/python/fitting/ex02_FitBasics/FitCylindersPrisms_new.py
- Examples/python/fitting/ex11_ExternalMinimizer/lmfit_basics_new.py
- Fit/Kernel/Parameters.cpp
- Fit/Kernel/Parameters.h
- Tests/Functional/Python/PyFit/minimizer_api.py
- Tests/UnitTests/Fit/Kernel/ParametersTest.h
- Wrap/swig/extendCore.i
- Wrap/swig/extendFit.i
- Wrap/swig/libBornAgainCore.i
- Wrap/swig/renameCore.i
- Wrap/swig/renameFit.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainFit.py
- auto/Wrap/libBornAgainFit_wrap.cpp
On the way to use FitObjective from lmfit.
* In general works, see lmfit_basics_new.py.
* FitObjective has to be still switched from Fit::Parameters to more generic Python like dictionary.
> FitObjective adapted for lmfit.

- GUI/coregui/Models/BeamItems.h
- GUI/coregui/Models/InstrumentItems.h
- GUI/coregui/Models/RealDataItem.cpp
- GUI/coregui/Models/SpecularBeamInclinationItem.cpp
1. Fixed the crash related to loading RealDataItem linked to an instrument
2. Provided a better view for default SpecularSimulation
> Minor fixes for GUI

- GUI/coregui/Models/SessionModelDelegate.cpp
> Fix for crash on attempt to edit fit parameter value/limits

- Wrap/swig/libBornAgainCore.i
…lattice interference functions
> Fix bug #2131: Memory leak in factory methods when used from Python

- Core/Instrument/PyArrayImportUtils.cpp
- Core/Instrument/PyArrayImportUtils.h
- Tests/Functional/Python/PyCore/intensitydata.py
- Wrap/swig/libBornAgainCore.i
- auto/Wrap/libBornAgainCore.py
> importArrayToOutputData functions for easier OutputData handling

- Core/Computation/DWBAComputation.cpp
- GUI/coregui/Models/DataItem.cpp
- GUI/coregui/Models/DataItem.h
- GUI/coregui/Models/IntensityDataItem.cpp
- GUI/coregui/Models/JobItemUtils.cpp
- GUI/coregui/Views/IntensityDataWidgets/ColorMap.cpp
- GUI/coregui/Views/IntensityDataWidgets/IntensityDataWidget.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceWidget.cpp
- GUI/coregui/mainwindow/OutputDataIOService.cpp
- GUI/coregui/mainwindow/projectmanager.cpp
- Tests/Functional/Core/CoreSpecial/CoreIOTest.cpp
- Tests/Functional/Core/CoreSpecial/CoreIOTest.h
+ Bug 2168: Autosave leads to the GUI crash at certain conditions 
+ Bug 2161: Cancel of runnig job doesn't work properly
+ Bug 2162: Jobs which was autosaved during the run stays in running state after project restore.
> Autosave bug fixed

- GUI/coregui/Models/DataItem.cpp
- GUI/coregui/Models/DataItem.h
- GUI/coregui/Models/JobItemUtils.cpp
- GUI/coregui/Models/JobItemUtils.h
- GUI/coregui/mainwindow/OutputDataIOHistory.cpp
- GUI/coregui/mainwindow/OutputDataIOHistory.h
- GUI/coregui/mainwindow/OutputDataIOService.cpp
- GUI/coregui/mainwindow/OutputDataIOService.h
- GUI/coregui/mainwindow/SaveLoadInterface.cpp
- GUI/coregui/mainwindow/SaveLoadInterface.h
- GUI/coregui/mainwindow/projectdocument.cpp
- Tests/UnitTests/GUI/TestOutputDataIOService.h
Extracting common interface for save/load non-XML data is required by future using of PointwiseAxis in GUI, since it will be necessary to save/load coordinate values to/from disk.
> To redmine issue 2177: extracted and employed save/load interface for non-XML data

- GUI/coregui/Views/IntensityDataWidgets/Plot1D.cpp
- GUI/coregui/Views/IntensityDataWidgets/Plot1D.h
In fitting widget for reflectometry experimental data was not updated properly.
> Fixed broken user data display on wavelength change during fit

- Tests/Functional/Python/PyCore/intensitydata_io.py
The new test makes explicit the difference in the data layout between OutputData objects and Numpy arrays.
> Added explicit test for RawDataVector - NumpyArray

- Tests/UnitTests/CMakeLists.txt
- Tests/UnitTests/GUI/CMakeLists.txt
- ThirdParty/common/gtest/CMakeLists.txt
- cmake/generic/modules/AddGTest.cmake
> Revert "Fixed unit test crash when LD_LIBRARY contains own libgtest"

- Core/Particle/FormFactorCrystal.h
- GUI/ba3d/ba3d/model/object.cpp
- GUI/ba3d/ba3d/model/object.h
- GUI/ba3d/ba3d/model/particles.cpp
- GUI/ba3d/ba3d/model/particles.h
- GUI/coregui/Models/MesoCrystalItem.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceMesoCrystalUtils.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceMesoCrystalUtils.h
Not all outer shapes of mesocrystal have been implemented - Dodecahedron, Icosahedron, Ripple1, Ripple2, TruncatedCube nad TruncatedSpheroid are missing.
> GUI3D Implement Mesocrystal

- Fit/RootAdapter/MinimizerResultUtils.cpp
- Fit/Tools/AttLimits.cpp
- GUI/coregui/Models/FitParameterItems.cpp
- GUI/coregui/Models/ParameterTreeItems.cpp
- GUI/coregui/Models/ParameterTreeItems.h
- GUI/coregui/Models/ParameterTuningModel.cpp
- GUI/coregui/Models/SessionModelDelegate.cpp
- GUI/coregui/Models/item_constants.h
- GUI/coregui/Views/JobWidgets/ScientificSpinBox.h
- GUI/coregui/Views/PropertyEditor/PropertyEditorFactory.cpp
- GUI/coregui/Views/PropertyEditor/PropertyEditorFactory.h
- Tests/Functional/GUI/GUISpecial/GUITranslationTest.cpp
The pull-request takes into account previous reviewer remarks.
The issue 2116 still needs to be solved separately, since it requires some changes and wiring
in `FitParameterItem`
> Redmine issue 2141: Fitting material parameters in GUI

- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/CsvDataColumn.h
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/CsvImportAssistant.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/CsvImportAssistant.h
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/CsvImportTable.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/CsvImportTable.h
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/DataSelector.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/DataSelector.h
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/TableContextMenu.cpp
- GUI/coregui/Views/ImportDataWidgets/CsvImportAssistant/TableContextMenu.h
- Tests/Functional/GUI/GUISpecial/CMakeLists.txt
- Tests/Functional/GUI/GUISpecial/CsvImportAssistantPerformanceTest.cpp
- Tests/Functional/GUI/GUISpecial/CsvImportAssistantPerformanceTest.h
- Tests/Functional/GUI/GUISpecial/GUISpecialTestFactory.cpp
- Tests/UnitTests/GUI/TestCsvImportAssistant.cpp
1. Feature: Select individual rows to discard.
2. Feature: Color in red invalid cells (not containing numbers or unsorted coordinates).
3. Fix: Treat multiple spaces as one when the column separator is itself a space.
4. Refactor: Move read performance unit test to a functional test.
> CsvImportAssistant fixes and new features.

- GUI/coregui/Views/WelcomeView.cpp
- GUI/coregui/Views/WelcomeView.h
- GUI/coregui/mainwindow/UpdateNotifier.cpp
- GUI/coregui/mainwindow/UpdateNotifier.h
- GUI/coregui/mainwindow/UpdateNotifierWidget.cpp
- GUI/coregui/mainwindow/UpdateNotifierWidget.h
- GUI/coregui/mainwindow/actionmanager.cpp
- GUI/coregui/mainwindow/mainwindow.cpp
- GUI/coregui/mainwindow/mainwindow.h
- GUI/main/main.cpp
Now the question "Do you want to check updates automatically" is embedded in SampleView, and not in QMessageBox
> Refactor update notifier

- GUI/coregui/Views/JobWidgets/JobRealTimeWidget.cpp
> Restore reuse of internal ParameterTuningWidget

- CHANGELOG
- Doc/Doxygen/Doxyfile
- VERSION.cmake
> Adapt VERSION and CHANGELOG (only added new release date, since not all

- Core/Instrument/UnitConverterUtils.cpp
- Core/Simulation/OffSpecSimulation.cpp
- Core/Simulation/OffSpecSimulation.h
- Core/StandardSamples/PlainMultiLayerBySLDBuilder.cpp
- Core/StandardSamples/ResonatorBuilder.cpp
- Core/StandardSamples/ResonatorBuilder.h
- Tests/Functional/Fit/FitObjective/CMakeLists.txt
- Tests/Functional/Fit/FitObjective/FitObjectiveTestCases.cpp
- Tests/Functional/Fit/FitObjective/FitObjectiveTestCases.h
- Tests/Functional/Fit/FitObjective/FitObjectiveTestFactory.cpp
- Tests/Functional/Fit/FitObjective/FitPlanCases.cpp
- Tests/Functional/Fit/FitObjective/FitPlanCases.h
- Tests/Functional/Fit/FitObjective/FitPlanFactory.cpp
+ minor clean-up in fit functional tests
> Redmine issue 2259: restore off-spec fitting functionality

- Core/Fitting/FitObjective.cpp
- Core/Instrument/ArrayUtils.cpp
- Core/Instrument/Convolve.cpp
- Core/Instrument/FourierTransform.cpp
- Core/Instrument/OutputData.cpp
- Wrap/swig/extendCore.i
- Wrap/swig/libBornAgainCore.i
- auto/Wrap/libBornAgainCore.py
* Leakage during the fit when Python simulation object was not destroyed properly
* Leakage in numpy array constructed in C++ and delivered to Python
* Leakage in fft plans cleanup
> Fix memory leakages in PythonAPI

- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilder.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceBuilderUtils.h
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceMesoCrystalUtils.cpp
- GUI/coregui/Views/RealSpaceWidgets/RealSpaceMesoCrystalUtils.h
- GUI/coregui/Views/RealSpaceWidgets/TransformTo3D.cpp
* for the case then particles are in intermediate layer
> Fix position on particles in 3D view

- GUI/coregui/Views/PropertyEditor/CustomEditors.cpp
- GUI/coregui/Views/PropertyEditor/CustomEditors.h
- GUI/coregui/Views/PropertyEditor/PropertyEditorFactory.cpp
Fixes model update when ScientificSpinBox loses the focus
> Wrap ScientifcSpinBox into custom editor

- Examples/python/fitting/ex01_BasicExamples/basic_fitting_tutorial.py
- GUI/coregui/Views/MaterialEditor/MaterialItemUtils.cpp
This resolves http://apps.jcns.fz-juelich.de/redmine/issues/2342
> Bug fix for static QString initialization

- Core/HardParticle/FormFactorLongRipple1Gauss.cpp
- Core/HardParticle/FormFactorLongRipple1Gauss.h
- Core/HardParticle/FormFactorLongRipple1Lorentz.cpp
- Core/HardParticle/FormFactorLongRipple1Lorentz.h
- Wrap/swig/extendCore.i
- auto/Wrap/libBornAgainCore.py
+ Long sinusoidal ripple now use same math as standard ripple
+ Add index operator for  SimulationResults (Python)
> Sinusoidal ripple speed-up

- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorHBar.cpp
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorHBar.h
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorWidget.cpp
- GUI/coregui/Views/ImportDataWidgets/RealDataSelectorWidget.h
- GUI/coregui/coregui.qrc
- GUI/coregui/images/toolbar24dark_hambar.svg
Attempt to solve the problem with obscured rotate-dataset-action by adding hamburger-like button.
> New button in ImportDataView selector

- cmake/generic/modules/FindFFTW.cmake
Also make CMake rising an error when only static version of fftw3 is present on the system.
> Simplify CMake search of fftw3

- CHANGELOG
- Doc/Doxygen/Doxyfile
- VERSION.cmake
- auto/Wrap/doxygen_core.i
- auto/Wrap/doxygen_fit.i
- auto/Wrap/libBornAgainCore.py
Note that issues [2075](http://apps.jcns.fz-juelich.de/redmine/issues/2075) and [2381](http://apps.jcns.fz-juelich.de/redmine/issues/2381) are not included in the change log for now (since are not yet closed)
> Update version, py docs and regenerate bindings for the release-1.16.0

- GUI/coregui/Views/IntensityDataWidgets/SavePlotAssistant.cpp
This pull request solves the bug reported in Issue 2408: "Unable to save png, jpg and pdf" (http://apps.jcns.fz-juelich.de/redmine/issues/2408).
> Fix Bug #2408: Unable to save jpg, pdf and png

- Core/Computation/MultiLayerUtils.cpp
- Core/Computation/MultiLayerUtils.h
- Core/Computation/ProcessedSample.cpp
- Core/Computation/SpecularComputation.cpp
- Core/Computation/SpecularComputationTerm.cpp
- Core/Computation/SpecularComputationTerm.h
- Core/Multilayer/IFresnelMap.cpp
- Core/Multilayer/IFresnelMap.h
- Core/Multilayer/MatrixFresnelMap.cpp
- Core/Multilayer/MatrixFresnelMap.h
- Core/Multilayer/MultiLayer.cpp
- Core/Multilayer/MultiLayer.h
- Core/Multilayer/ScalarFresnelMap.cpp
- Core/Multilayer/ScalarFresnelMap.h
- Core/Multilayer/SpecularStrategyBuilder.cpp
- Core/Multilayer/SpecularStrategyBuilder.h
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainFit_wrap.cpp
Prepare the codebase to add Nevot-Croce Roughness model
> Make strategy for specular computation switchable

- Core/Material/MaterialBySLDImpl.cpp
- Core/Material/RefractiveMaterialImpl.cpp
- Core/Multilayer/MultiLayer.cpp
Added error checking for invalid user input as described in
http://apps.jcns.fz-juelich.de/redmine/issues/2441
http://apps.jcns.fz-juelich.de/redmine/issues/2442
At a lower level it is still possible to create unphysical simulations.
> Provide error checking for invalid input (issue #2441/2442)

- Examples/python/simulation/ex06_Reflectometry/RoughnessModel.py
Add the new Python example to the source tree that demonstrates how to change the roughness model in a simulation.
> Add Python example RoughnessModel

- Core/Beam/Beam.h
- Core/Beam/FootprintFactorGaussian.h
- Core/Beam/FootprintFactorSquare.h
- Core/Beam/IFootprintFactor.h
- Core/Binning/IPixel.h
- Core/Instrument/AxisNames.h
- Core/Instrument/ConvolutionDetectorResolution.h
- Core/Instrument/DetectionProperties.h
- Core/Instrument/DetectorContext.h
- Core/Instrument/DetectorFunctions.h
- Core/Instrument/DetectorMask.h
- Core/Instrument/IDetector.h
- Core/Instrument/IDetector2D.h
- Core/Instrument/IUnitConverter.h
- Core/Instrument/Instrument.h
- Core/Instrument/IsGISAXSDetector.h
- Core/Instrument/RectangularDetector.h
- Core/Instrument/RegionOfInterest.h
- Core/Instrument/SimulationArea.h
- Core/Instrument/SimulationAreaIterator.h
- Core/Instrument/SimulationResult.h
- Core/Instrument/SpecularDetector1D.h
- Core/Instrument/SphericalDetector.h
- Core/Multilayer/KzComputation.h
- Doc/Doxygen/defgroups.dox
- Doc/Doxygen/mainpage.dox
- Doc/Doxygen/userapi.dox
Also update entry page.
This resolves http://apps.jcns.fz-juelich.de/redmine/issues/2385
> Doxygen: move instrument description out of group "simulation"

- Core/Computation/SpecularComputationTerm.h
- Core/Multilayer/ISpecularStrategy.h
- Core/Multilayer/SpecularMagneticStrategy.h
- Core/Multilayer/SpecularScalarNCStrategy.h
- Core/Multilayer/SpecularScalarStrategy.h
- Core/Multilayer/SpecularScalarTanhStrategy.h
Updated the doxygen comments that were forgotten in the recent round of changes.
> Updated doxygen comments

- Core/Instrument/OutputData.cpp
- Core/Instrument/OutputData.h
- Core/Instrument/SimulationResult.cpp
- Core/Tools/PyEmbeddedUtils.cpp
- Core/Tools/PyEmbeddedUtils.h
- Core/Tools/PyImport.cpp
- Core/Tools/PyImport.h
- GUI/coregui/mainwindow/PyImportAssistant.cpp
- GUI/coregui/mainwindow/PyImportAssistant.h
- GUI/coregui/mainwindow/actionmanager.cpp
- GUI/coregui/mainwindow/actionmanager.h
Alternatively, we could discuss dropping the BORNAGAIN_PYTHON flag for good
> Restore compilation for BORNAGAIN_PYTHON=OFF

- Examples/python/utils/plot_intensity_data.py
- Examples/python/utils/plot_intensity_data_diff.py
- Examples/python/utils/show2d.py
- Examples/python/utils/show2d_root.py
- Wrap/swig/doxy2swig.py
Trivial - I'll merge as soon as the tests pass
> Python scripts: in shebang line, request Python3

- Core/Instrument/PyArrayImportUtils.h
- Core/Instrument/SimulationResult.h
- Core/Material/Material.cpp
- Core/Material/Material.h
- Wrap/swig/directors.i
- Wrap/swig/warnings.i
- auto/Wrap/doxygenCore.i
- auto/Wrap/libBornAgainCore.py
- auto/Wrap/libBornAgainCore_wrap.h
- cmake/BornAgain/SwigLib.cmake
Builds on previous PR (branch det6)
> Scrutinize and comment Wrap/swig/warnings.i

- Doc/Doxygen/Doxyfile.long.in
- Doc/Doxygen/Doxyfile.user.in
- Doc/PhysicsManual/fig/drawing/Green.py
- Examples/Demos/simul_demo_cyl_SSCA.py
- Examples/Demos/simul_demo_cylsphere.py
- Examples/Demos/simul_demo_lattice1.py
- Examples/Demos/simul_demo_lattice2.py
- Examples/Demos/simul_demo_movie.py
- Examples/Demos/simul_demo_movie2.py
- Examples/Demos/simul_demo_movie3.py
- Examples/Python/utils/plot_diff_int.py
- Examples/Python/utils/plot_int.py
- Wrap/Python/bornagain_python_install.py
- Wrap/Python/plot_utils.py
- devtools/code-tools/print-includes.py
- devtools/code-tools/update-website.py
In webdoc, all simulated images now reside in static/files/simulated.
> devtools/update-website: write log file, adapt to changed directory structure in webdoc

- GUI/coregui/mainwindow/newprojectdialog.cpp
- GUI/coregui/mainwindow/newprojectdialog.h
- GUI/coregui/mainwindow/projectmanager.cpp
- GUI/coregui/mainwindow/projectmanager.h
Fixes crash on save project (see #1117)
> Issue 1117 crash on save project

- GUI/coregui/mainwindow/SaveService.cpp
- Tests/UnitTests/GUI/TestSaveService.cpp
> Issue 1136 crash after failed save

- GUI/coregui/Views/WelcomeView.cpp
- GUI/coregui/mainwindow/actionmanager.cpp
- GUI/coregui/mainwindow/mainwindow.cpp
- GUI/coregui/mainwindow/mainwindow.h
- GUI/coregui/mainwindow/newprojectdialog.cpp
This covers mainly:
* Fix of "Windows: Native representation of paths is wrong" (http://apps.jcns.fz-juelich.de/redmine/issues/2502)
* add missing accelerator keys to menu entries
* handle view selection buttons in regards to high dpi devices
> GUI refactorings and corrections 2
